export const FilterActionTypes = {
  SEARCH_REQUEST: 'SEARCH_REQUEST',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_FAILURE: 'SEARCH_FAILURE',

  SET_CURRENT_SEARCH: 'SET_CURRENT_SEARCH',
  DELETE_CURRENT_SEARCH: 'DELETE_CURRENT_SEARCH',
  SET_CATEGORY_FILTER: 'SET_CATEGORY_FILTER',
  SET_SEARCH_TYPE: 'SET_SEARCH_TYPE',

  GET_CART_LANGAGE_REQUEST: 'GET_CART_LANGAGE_REQUEST',
  GET_CART_LANGAGE_SUCESS: 'GET_CART_LANGAGE_SUCESS',
  GET_CART_LANGAGE_FAILURE: 'GET_CART_LANGAGE_FAILURE'

}