export const FilterActionTypes = {
  SEARCH_REQUEST: 'SEARCH_REQUEST',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_FAILURE: 'SEARCH_FAILURE',

  GET_CART_LANGAGE_REQUEST: 'GET_CART_LANGAGE_REQUEST',
  GET_CART_LANGAGE_SUCESS: 'GET_CART_LANGAGE_SUCESS',
  GET_CART_LANGAGE_FAILURE: 'GET_CART_LANGAGE_FAILURE'

}