export const FilterActionTypes = {
  SET_CURRENT_SEARCH: 'SET_CURRENT_SEARCH',
  DELETE_CURRENT_SEARCH: 'DELETE_CURRENT_SEARCH',
  SET_CATEGORY_FILTER: 'SET_CATEGORY_FILTER',
  SET_TYPE: 'SET_TYPE',

  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_FAILURE: 'SEARCH_FAILURE',
  
  GET_CARDS_LANGAGE_CATEGORY_REQUEST: 'GET_CARDS_LANGAGE_CATEGORY_REQUEST',
  GET_CARDS_LANGAGE_CATEGORY_SUCCESS: 'GET_CARDS_LANGAGE_CATEGORY_SUCCESS',
  GET_CARDS_LANGAGE_CATEGORY_FAILURE: 'GET_CARDS_LANGAGE_CATEGORY_FAILURE'
}