export const LayoutActionTypes = {
  SHOW_POPUP_CARD: 'SHOW_POPUP_CARD',
  CLOSE_POPUP_CARD: 'CLOSE_POPUP_CARD',
  SHOW_FULLSCREEN: 'SHOW_FULLSCREEN',
  CLOSE_FULLSCREEN: 'CLOSE_FULLSCREEN',
  TOGGLE_USER_NAV: 'TOGGLE_USER_NAV',
  OPEN_MOBILE_NAV: 'OPEN_MOBILE_NAV',
  CLOSE_MOBILE_NAV: 'CLOSE_MOBILE_NAV',
}