export const CardsActionTypes = {
  SET_CLICKED_CARD: 'SET_CLICKED_CARD',
  SET_NO_CLICKED_CARD: 'SET_NO_CLICKED_CARD',


  GET_ALL_CARDS_SUCCESS: 'GET_ALL_CARDS_SUCCESS',
  GET_ALL_CARDS_FAILURE: 'GET_ALL_CARDS_FAILURE'

}