export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_OTHER_USER: 'SET_OTHER_USER',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCESS: 'LOGIN_SUCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  SET_CLICKED_USER: 'SET_CLICKED_USER',
  GET_CLICKED_USER_ERROR: 'GET_CLICKED_USER_ERROR'
}